### ISSUE TITLE
Error when running in Laravel Vapor (AWS Lambda) Environment

### ISSUE THREAD

**Issue by eberkund** [thephpleague/uri-hostname-parser#7]
## Issue summary

Library works in dev and plain ol' VPS environment but fails using the new [Laravel Vapor](https://vapor.laravel.com/) environment based on AWS Lambda.

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Uri\PublicSuffix version | 1.1.1  |
| PHP version | 7.3.9 |
| OS Platform | Laravel Vapor/AWS Lambda |

## Standalone code, or other way to reproduce the problem

```
$host = new Host(Http::createFromString(request()->getUri())->getHost());
$subdomain = $host->getSubDomain();
```

### Expected result

To not throw an exception and to return the subdomain.

### Actual result

Here is my Sentry stack trace:

```
Exception(most recent call first)

League\Uri\PublicSuffix\Exception: Unable to load the public suffix list rules for https://publicsuffix.org/list/public_suffix_list.dat
#66 /vendor/league/uri-hostname-parser/src/PublicSuffix/ICANNSectionManager.php(70): League\Uri\PublicSuffix\ICANNSectionManager::getRules
#65 /vendor/league/uri-components/src/Components/Host.php(459): League\Uri\Components\Host::lazyloadInfo
#64 /vendor/league/uri-components/src/Components/Host.php(425): League\Uri\Components\Host::__debugInfo
#63 /vendor/symfony/var-dumper/Caster/Caster.php(86): Symfony\Component\VarDumper\Caster\Caster::castObject
#62 /vendor/symfony/var-dumper/Cloner/AbstractCloner.php(319): Symfony\Component\VarDumper\Cloner\AbstractCloner::castObject
#61 /vendor/symfony/var-dumper/Cloner/VarCloner.php(189): Symfony\Component\VarDumper\Cloner\VarCloner::doClone
#60 /vendor/symfony/var-dumper/Cloner/AbstractCloner.php(257): Symfony\Component\VarDumper\Cloner\AbstractCloner::cloneVar
#59 /vendor/beyondcode/laravel-dump-server/src/Dumper.php(39): BeyondCode\DumpServer\Dumper::dump
#58 /vendor/beyondcode/laravel-dump-server/src/DumpServerServiceProvider.php(53): BeyondCode\DumpServer\DumpServerServiceProvider::BeyondCode\DumpServer\{closure}
#57 /vendor/symfony/var-dumper/VarDumper.php(46): Symfony\Component\VarDumper\VarDumper::dump
#56 /vendor/symfony/var-dumper/Resources/functions/dump.php(20): dump
#55 /routes/web.php(17): Illuminate\Routing\RouteFileRegistrar::{closure}
#54 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route::runCallable
#53 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(179): Illuminate\Routing\Route::run
#52 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#51 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#50 /app/Http/Middleware/AddTenantMiddleware.php(86): App\Http\Middleware\AddTenantMiddleware::handle
#49 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#48 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Middleware\SubstituteBindings::handle
#47 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#46 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
#45 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#44 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\View\Middleware\ShareErrorsFromSession::handle
#43 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#42 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Session\Middleware\StartSession::handle
#41 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#40 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
#39 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#38 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Cookie\Middleware\EncryptCookies::handle
#37 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#36 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline::then
#35 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\Router::runRouteWithinStack
#34 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router::runRoute
#33 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router::dispatchToRoute
#32 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router::dispatch
#31 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#30 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#29 /vendor/kabbouchi/nova-impersonate/src/Http/Middleware/Impersonate.php(24): KABBOUCHI\NovaImpersonate\Http\Middleware\Impersonate::handle
#28 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#27 /vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Laravel\Nova\Http\Middleware\ServeNova::handle
#26 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#25 /vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Barryvdh\Debugbar\Middleware\InjectDebugbar::handle
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /vendor/fideloper/proxy/src/TrustProxies.php(57): Fideloper\Proxy\TrustProxies::handle
#22 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#21 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#20 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#19 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#18 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#17 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Foundation\Http\Middleware\ValidatePostSize::handle
#16 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#15 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#13 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline::then
#12 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#11 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel::handle
#10 /vendor/laravel/vapor-core/src/Runtime/HttpKernel.php(60): Laravel\Vapor\Runtime\HttpKernel::Laravel\Vapor\Runtime\{closure}
#9 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#8 /vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureVanityUrlIsNotIndexed.php(16): Laravel\Vapor\Runtime\Http\Middleware\EnsureVanityUrlIsNotIndexed::handle
#7 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#6 /vendor/laravel/vapor-core/src/Runtime/Http/Middleware/RedirectStaticAssets.php(30): Laravel\Vapor\Runtime\Http\Middleware\RedirectStaticAssets::handle
#5 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#4 /vendor/laravel/vapor-core/src/Runtime/Http/Middleware/EnsureOnNakedDomain.php(25): Laravel\Vapor\Runtime\Http\Middleware\EnsureOnNakedDomain::handle
#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#2 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline::then
#1 /vendor/laravel/vapor-core/src/Runtime/HttpKernel.php(61): Laravel\Vapor\Runtime\HttpKernel::handle
#0 /httpHandler.php(58): null
```

**Comment by eberkund** [comment]
I started looking at the source code package and things are starting to make sense. Since the application caches the file with the domain info I am assuming it is running into problems saving this file to disk in the Lambda environment.

Is there a way to configure the cache provider?

**Comment by eberkund** [comment]
Nevermind, I figured out how to overload the default cache using the resolver constructor param.
